
apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "dev-traefik-lb"
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: web
  - name: websecure
    port: 443
    targetPort: websecure
  - name: dashboard
    port: 8080
    targetPort: dashboard
  selector:
    app: traefik
