apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: nginx
        image: rolandgryddynamics/main:latest  # Replace with your custom image
        ports:
        - containerPort: 8090  # Adjust containerPort to 8081
